spring.application.name=biosphere-backend
spring.threads.virtual.enabled=true
server.port=8080

# --- Configuration PostgreSQL ---
spring.datasource.url=jdbc:postgresql://localhost:5432/biospheredb
spring.datasource.username=greg
spring.datasource.password=secret
spring.datasource.driver-class-name=org.postgresql.Driver

# Demande à Hibernate de créer/mettre à jour la structure des tables automatiquement
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Pour voir les requêtes SQL dans la console (utile pour débugger)
spring.jpa.show-sql=true